-- SPDX-License-Identifier: MIT
-- Human Funnel Schema for Rustchain
-- Supports conversion tracking, referrals, micro-bounties, and hall of fame

PRAGMA foreign_keys = ON;

-- Users table for funnel participants
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    wallet_address TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE,
    email TEXT,
    referral_code TEXT UNIQUE NOT NULL,
    referred_by TEXT,
    stage INTEGER DEFAULT 1, -- 1=landing, 2=signup, 3=mining, 4=referral, 5=retention
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_active DATETIME DEFAULT CURRENT_TIMESTAMP,
    total_earnings_rtc REAL DEFAULT 0,
    hardware_type TEXT, -- old, medium, high
    is_active BOOLEAN DEFAULT 1,
    FOREIGN KEY (referred_by) REFERENCES users(referral_code)
);

-- Referral tracking and metrics
CREATE TABLE IF NOT EXISTS referrals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    referrer_code TEXT NOT NULL,
    referee_wallet TEXT NOT NULL,
    conversion_stage INTEGER DEFAULT 1, -- 1=clicked, 2=signed, 3=mining, 4=earned
    bonus_rtc REAL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    converted_at DATETIME,
    FOREIGN KEY (referrer_code) REFERENCES users(referral_code),
    FOREIGN KEY (referee_wallet) REFERENCES users(wallet_address)
);

-- Micro-bounties for Stage 4 conversion
CREATE TABLE IF NOT EXISTS micro_bounties (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    reward_rtc REAL NOT NULL,
    time_limit_minutes INTEGER DEFAULT 10,
    difficulty TEXT DEFAULT 'beginner', -- beginner, easy, medium
    requirements TEXT, -- JSON array of steps
    verification_type TEXT DEFAULT 'auto', -- auto, manual, proof
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Micro-bounty completions
CREATE TABLE IF NOT EXISTS bounty_completions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bounty_id INTEGER NOT NULL,
    user_wallet TEXT NOT NULL,
    proof_data TEXT, -- JSON with screenshots, answers, etc
    status TEXT DEFAULT 'submitted', -- submitted, verified, rejected, paid
    reward_paid_rtc REAL DEFAULT 0,
    completed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    verified_at DATETIME,
    FOREIGN KEY (bounty_id) REFERENCES micro_bounties(id),
    FOREIGN KEY (user_wallet) REFERENCES users(wallet_address)
);

-- Brag cards generated by users
CREATE TABLE IF NOT EXISTS brag_cards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_wallet TEXT NOT NULL,
    card_type TEXT NOT NULL, -- earnings, referrals, mining_streak, hardware_upgrade
    template_name TEXT NOT NULL,
    generated_data TEXT NOT NULL, -- JSON with all card fields
    image_path TEXT,
    share_count INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_public BOOLEAN DEFAULT 1,
    FOREIGN KEY (user_wallet) REFERENCES users(wallet_address)
);

-- Weekly hall of fame entries
CREATE TABLE IF NOT EXISTS hall_of_fame (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    week_start DATE NOT NULL,
    category TEXT NOT NULL, -- top_earner, top_referrer, most_bounties, hardware_hero
    rank_position INTEGER NOT NULL,
    user_wallet TEXT NOT NULL,
    metric_value REAL NOT NULL, -- earnings, referral count, bounties completed
    prize_rtc REAL DEFAULT 0,
    is_paid BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_wallet) REFERENCES users(wallet_address)
);

-- Conversion funnel metrics
CREATE TABLE IF NOT EXISTS funnel_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE NOT NULL,
    stage INTEGER NOT NULL,
    user_count INTEGER DEFAULT 0,
    conversion_rate REAL DEFAULT 0,
    avg_time_to_next_stage REAL, -- hours
    bounce_rate REAL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Landing page interactions
CREATE TABLE IF NOT EXISTS landing_interactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    user_wallet TEXT,
    action_type TEXT NOT NULL, -- view, click_start, click_learn, signup_attempt
    element_clicked TEXT,
    referral_source TEXT,
    hardware_detected TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_wallet) REFERENCES users(wallet_address)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_referral_code ON users(referral_code);
CREATE INDEX IF NOT EXISTS idx_users_stage ON users(stage);
CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_code);
CREATE INDEX IF NOT EXISTS idx_bounty_completions_user ON bounty_completions(user_wallet);
CREATE INDEX IF NOT EXISTS idx_brag_cards_user ON brag_cards(user_wallet);
CREATE INDEX IF NOT EXISTS idx_hall_of_fame_week ON hall_of_fame(week_start, category);
CREATE INDEX IF NOT EXISTS idx_landing_interactions_session ON landing_interactions(session_id);

-- Insert default micro-bounties for non-technical users
INSERT OR IGNORE INTO micro_bounties (title, description, reward_rtc, time_limit_minutes, requirements, verification_type) VALUES
('First Mining Setup', 'Download and start mining for 5 minutes on any hardware', 2.5, 10, '["Download miner", "Start mining", "Run for 5 minutes", "Take screenshot"]', 'proof'),
('Share Your First Block', 'Post about your mining experience on social media', 1.5, 8, '["Take mining screenshot", "Post to Twitter/Facebook", "Use #RustchainMining hashtag", "Submit link"]', 'manual'),
('Hardware Health Check', 'Check your computer specs and submit hardware report', 1.0, 5, '["Run system info check", "Note CPU/RAM/Storage", "Submit hardware form", "Get optimization tips"]', 'auto');
