# SPDX-License-Identifier: MIT
"""Generate contract reference docs and validate their local links."""

from __future__ import annotations

import ast
import json
import re
import urllib.parse
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from .contract import REPOSITORY_ROOT


GENERATED_HEADER = (
    "<!-- Generated by `python3 -m compatibility_lab generate-docs`. "
    "Do not edit by hand. -->"
)
INLINE_LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
REFERENCE_LINK_RE = re.compile(r"^\s*\[[^\]]+\]:\s*(\S+)", re.MULTILINE)
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*#*\s*$", re.MULTILINE)
URL_RE = re.compile(r"https?://[^\s<>\])\"'`]+")
CODE_SPAN_RE = re.compile(r"`([^`]+)`")


def _iter_operations(contract: Mapping[str, Any]):
    for path, path_item in contract["paths"].items():
        yield path, path_item["get"]


def _escape_cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _component_name(reference: str) -> str:
    return reference.rsplit("/", 1)[-1]


def _schema_type(schema: Mapping[str, Any]) -> str:
    if "$ref" in schema:
        return _component_name(str(schema["$ref"]))
    schema_type = schema.get("type", "any")
    if isinstance(schema_type, list):
        return " or ".join(str(item) for item in schema_type)
    if schema_type == "array" and isinstance(schema.get("items"), Mapping):
        return f"{_schema_type(schema['items'])}[]"
    return str(schema_type)


def _constraints(schema: Mapping[str, Any]) -> str:
    values: List[str] = []
    if "const" in schema:
        values.append(f"constant `{json.dumps(schema['const'], separators=(',', ':'))}`")
    if "enum" in schema:
        values.append(
            "one of "
            + ", ".join(
                f"`{json.dumps(item, separators=(',', ':'))}`" for item in schema["enum"]
            )
        )
    if "minimum" in schema:
        values.append(f">= {schema['minimum']}")
    if "maximum" in schema:
        values.append(f"<= {schema['maximum']}")
    if "minLength" in schema:
        values.append(f"min length {schema['minLength']}")
    if "maxLength" in schema:
        values.append(f"max length {schema['maxLength']}")
    if "pattern" in schema:
        values.append(f"pattern `{schema['pattern']}`")
    if "default" in schema:
        values.append(f"default `{schema['default']}`")
    return "; ".join(values) or "-"


def _response_schema(response: Mapping[str, Any]) -> Mapping[str, Any]:
    return response["content"]["application/json"]["schema"]


def generate_reference(contract: Mapping[str, Any]) -> str:
    """Render deterministic Markdown directly from the canonical contract."""

    info = contract["info"]
    metadata = contract["x-rustchain-compatibility"]
    lines = [
        GENERATED_HEADER,
        "",
        f"# {info['title']}",
        "",
        str(info["description"]).strip(),
        "",
        "The canonical machine-readable source is "
        "[`compatibility_lab/read_only_api.openapi.json`](../compatibility_lab/read_only_api.openapi.json). "
        "This reference is checked in for review and must be regenerated whenever the contract changes.",
        "",
        "## Safety Boundary",
        "",
        "The compatibility surface is public and read-only. The lab sends only `GET`, "
        "never sends a request body or credentials, keeps TLS verification enabled, and is "
        "never pointed at a live node by CI.",
        "",
        "## Endpoints",
        "",
        "| Method | Path | Operation | Implementation |",
        "|---|---|---|---|",
    ]

    for path, operation in _iter_operations(contract):
        implementation = operation["x-rustchain-implementation"]
        source = str(implementation["file"])
        handler = str(implementation["handler"])
        lines.append(
            f"| `GET` | `{_escape_cell(path)}` | {_escape_cell(operation['summary'])} | "
            f"[`{_escape_cell(handler)}`](../{source}) |"
        )

    for path, operation in _iter_operations(contract):
        lines.extend(
            [
                "",
                f"## `GET {path}`",
                "",
                str(operation.get("description", operation["summary"])).strip(),
                "",
            ]
        )
        parameters = operation.get("parameters", [])
        if parameters:
            lines.extend(
                [
                    "### Query Parameters",
                    "",
                    "| Name | Required | Type | Constraints | Description |",
                    "|---|---|---|---|---|",
                ]
            )
            for parameter in parameters:
                schema = parameter.get("schema", {})
                lines.append(
                    f"| `{_escape_cell(parameter['name'])}` | "
                    f"{'yes' if parameter.get('required') else 'no'} | "
                    f"`{_escape_cell(_schema_type(schema))}` | "
                    f"{_escape_cell(_constraints(schema))} | "
                    f"{_escape_cell(parameter.get('description', '-'))} |"
                )
            lines.append("")
        else:
            lines.extend(["Query parameters: none.", ""])

        lines.extend(
            [
                "### Responses",
                "",
                "| Status | Schema | Meaning |",
                "|---|---|---|",
            ]
        )
        for status, response in operation["responses"].items():
            schema_name = _schema_type(_response_schema(response))
            lines.append(
                f"| `{status}` | `{_escape_cell(schema_name)}` | "
                f"{_escape_cell(response['description'])} |"
            )

        lines.extend(["", "Offline fixtures:"])
        for fixture_name in operation["x-rustchain-fixtures"]:
            lines.append(
                f"- [`{fixture_name}`]"
                f"(../{metadata['fixtures_directory']}/{fixture_name})"
            )

    lines.extend(["", "## Schemas", ""])
    for name, schema in contract["components"]["schemas"].items():
        lines.extend([f"### `{name}`", "", str(schema.get("description", "")).strip(), ""])
        if schema.get("type") != "object":
            lines.extend([f"Type: `{_schema_type(schema)}`", ""])
            continue
        lines.extend(
            [
                "| Field | Type | Required | Constraints | Description |",
                "|---|---|---|---|---|",
            ]
        )
        required = set(schema.get("required", []))
        for field, field_schema in schema.get("properties", {}).items():
            lines.append(
                f"| `{_escape_cell(field)}` | `{_escape_cell(_schema_type(field_schema))}` | "
                f"{'yes' if field in required else 'no'} | "
                f"{_escape_cell(_constraints(field_schema))} | "
                f"{_escape_cell(field_schema.get('description', '-'))} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Verification",
            "",
            "From the repository root:",
            "",
            "```bash",
            "python3 -m compatibility_lab validate",
            "python3 -m compatibility_lab generate-docs --check",
            "python3 -m compatibility_lab check-links",
            "```",
            "",
            "A live compatibility probe is explicit and optional:",
            "",
            "```bash",
            "python3 -m compatibility_lab probe https://node.example --miner-id compatibility-probe",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def generated_reference_path(
    contract: Mapping[str, Any], repository_root: Path = REPOSITORY_ROOT
) -> Path:
    metadata = contract["x-rustchain-compatibility"]
    return repository_root / str(metadata["generated_reference"])


def write_reference(
    contract: Mapping[str, Any], repository_root: Path = REPOSITORY_ROOT
) -> Path:
    path = generated_reference_path(contract, repository_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_reference(contract), encoding="utf-8")
    return path


def stale_reference_error(
    contract: Mapping[str, Any], repository_root: Path = REPOSITORY_ROOT
) -> Optional[str]:
    path = generated_reference_path(contract, repository_root)
    expected = generate_reference(contract)
    try:
        actual = path.read_text(encoding="utf-8")
    except OSError as exc:
        return f"could not read generated reference {path}: {exc}"
    if actual != expected:
        return (
            f"generated reference is stale: {path.relative_to(repository_root)}; "
            "run python3 -m compatibility_lab generate-docs"
        )
    return None


def configured_link_files(
    contract: Mapping[str, Any], repository_root: Path = REPOSITORY_ROOT
) -> List[Path]:
    metadata = contract["x-rustchain-compatibility"]
    return [repository_root / str(path) for path in metadata["link_check_files"]]


def configured_route_files(
    contract: Mapping[str, Any], repository_root: Path = REPOSITORY_ROOT
) -> List[Path]:
    metadata = contract["x-rustchain-compatibility"]["documentation_route_check"]
    return [repository_root / str(path) for path in metadata["files"]]


def _github_slug(value: str) -> str:
    value = re.sub(r"<[^>]+>", "", value).strip().lower()
    value = re.sub(r"[^\w\- ]", "", value, flags=re.UNICODE)
    return re.sub(r"\s+", "-", value)


def _heading_anchors(path: Path) -> set:
    text = path.read_text(encoding="utf-8")
    anchors = set()
    counts: Dict[str, int] = {}
    for heading in HEADING_RE.findall(text):
        base = _github_slug(heading)
        count = counts.get(base, 0)
        anchor = base if count == 0 else f"{base}-{count}"
        counts[base] = count + 1
        anchors.add(anchor)
    return anchors


def _link_targets(text: str) -> Iterable[str]:
    for match in INLINE_LINK_RE.finditer(text):
        raw = match.group(1).strip()
        if raw.startswith("<") and ">" in raw:
            yield raw[1 : raw.index(">")]
        else:
            yield raw.split(None, 1)[0]
    yield from REFERENCE_LINK_RE.findall(text)


def _is_external(target: str) -> bool:
    lowered = target.lower()
    return lowered.startswith(
        ("http://", "https://", "mailto:", "tel:", "data:", "javascript:")
    ) or target.startswith("/")


def check_local_links(
    files: Sequence[Path], repository_root: Path = REPOSITORY_ROOT
) -> List[str]:
    """Find missing local Markdown targets and invalid Markdown anchors."""

    root = repository_root.resolve()
    errors: List[str] = []
    anchor_cache: Dict[Path, set] = {}
    for source in files:
        source = Path(source)
        try:
            text = source.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            errors.append(f"{source}: could not read Markdown file: {exc}")
            continue
        for target in _link_targets(text):
            if not target or _is_external(target):
                continue
            decoded = urllib.parse.unquote(target)
            path_part, separator, fragment = decoded.partition("#")
            target_path = source if not path_part else source.parent / path_part
            resolved = target_path.resolve()
            try:
                resolved.relative_to(root)
            except ValueError:
                errors.append(f"{source}: local link escapes repository: {target}")
                continue
            if not resolved.exists():
                errors.append(f"{source}: missing local link target: {target}")
                continue
            if separator and fragment and resolved.suffix.lower() in {".md", ".markdown"}:
                if resolved not in anchor_cache:
                    try:
                        anchor_cache[resolved] = _heading_anchors(resolved)
                    except (OSError, UnicodeError) as exc:
                        errors.append(f"{source}: could not inspect anchor target {target}: {exc}")
                        continue
                if fragment.lower() not in anchor_cache[resolved]:
                    errors.append(f"{source}: missing local link anchor: {target}")
    return errors


def _literal_string_list(node: ast.AST) -> Optional[List[str]]:
    if not isinstance(node, (ast.List, ast.Tuple)):
        return None
    values: List[str] = []
    for item in node.elts:
        if not isinstance(item, ast.Constant) or not isinstance(item.value, str):
            return None
        values.append(item.value.upper())
    return values


def _get_routes_from_source(path: Path) -> Tuple[set, List[str]]:
    """Extract literal Flask GET route decorators from an authoritative source."""

    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except (OSError, UnicodeError, SyntaxError) as exc:
        return set(), [f"{path}: could not parse authoritative routes: {exc}"]

    routes = set()
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            function = decorator.func
            if not isinstance(function, ast.Attribute) or function.attr != "route":
                continue
            if not decorator.args:
                continue
            route_node = decorator.args[0]
            if not isinstance(route_node, ast.Constant) or not isinstance(route_node.value, str):
                continue
            methods: Optional[List[str]] = None
            for keyword in decorator.keywords:
                if keyword.arg == "methods":
                    methods = _literal_string_list(keyword.value)
                    break
            if methods is None or "GET" in methods:
                routes.add(route_node.value)
    return routes, []


def _normalize_route(path: str) -> str:
    decoded = urllib.parse.unquote(path)
    normalized = "/" + decoded.lstrip("/")
    return normalized if normalized == "/" else normalized.rstrip("/")


def _route_pattern(route: str) -> re.Pattern:
    parts: List[str] = []
    cursor = 0
    for match in re.finditer(r"<(?:(?:[^:<>]+):)?[^<>]+>", route):
        parts.append(re.escape(route[cursor : match.start()]))
        parts.append(r"[^/]+")
        cursor = match.end()
    parts.append(re.escape(route[cursor:]))
    return re.compile("^" + "".join(parts) + "/?$")


def _is_implemented_route(candidate: str, implemented: Iterable[str]) -> bool:
    candidate = _normalize_route(candidate)
    return any(_route_pattern(route).fullmatch(candidate) for route in implemented)


def _documented_route_candidates(
    line: str,
    public_hosts: set,
    route_prefixes: Sequence[str],
    exact_routes: set,
) -> set:
    candidates = set()
    for raw_url in URL_RE.findall(line):
        parsed = urllib.parse.urlsplit(raw_url.rstrip(".,;:`"))
        if parsed.hostname in public_hosts:
            candidates.add(_normalize_route(parsed.path))
    for target in _link_targets(line):
        parsed = urllib.parse.urlsplit(target)
        if target.startswith("/") or parsed.hostname in public_hosts:
            candidates.add(_normalize_route(parsed.path))
    for code in CODE_SPAN_RE.findall(line):
        for token in code.split():
            path = token.split("?", 1)[0].rstrip(".,;:")
            if path.startswith("/"):
                candidates.add(_normalize_route(path))
    return {
        route
        for route in candidates
        if route in exact_routes or any(route.startswith(prefix) for prefix in route_prefixes)
    }


def check_documented_routes(
    contract: Mapping[str, Any], repository_root: Path = REPOSITORY_ROOT
) -> List[str]:
    """Report API routes claimed by docs but absent from the integrated node."""

    config = contract["x-rustchain-compatibility"]["documentation_route_check"]
    implemented = set()
    errors: List[str] = []
    for raw_source in config["authoritative_sources"]:
        routes, source_errors = _get_routes_from_source(repository_root / str(raw_source))
        implemented.update(_normalize_route(route) for route in routes)
        errors.extend(source_errors)
    if errors:
        return errors

    public_hosts = {str(host).lower() for host in config["public_hosts"]}
    route_prefixes = tuple(str(prefix) for prefix in config["route_prefixes"])
    exact_routes = {_normalize_route(str(route)) for route in config["exact_routes"]}
    for path in configured_route_files(contract, repository_root):
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeError) as exc:
            errors.append(f"{path}: could not read route documentation: {exc}")
            continue
        for line_number, line in enumerate(lines, start=1):
            candidates = _documented_route_candidates(
                line, public_hosts, route_prefixes, exact_routes
            )
            for candidate in sorted(candidates):
                if not _is_implemented_route(candidate, implemented):
                    errors.append(
                        f"{path}:{line_number}: documented GET route is not registered "
                        f"by the authoritative node: {candidate}"
                    )
    return errors
