name: RustChain Mining Status Badge
description: Updates a README badge for RustChain mining status
author: Scottcjn
branding:
  icon: cpu
  color: blue
inputs:
  wallet:
    description: RustChain wallet identifier for /api/badge/{wallet}
    required: true
  readme-path:
    description: Path to README file to update
    required: false
    default: README.md
  badge-style:
    description: Shields.io badge style for the endpoint URL
    required: false
    default: flat-square
runs:
  using: composite
  steps:
    - name: Update mining badge block
      shell: bash
      run: |
        export WALLET="${{ inputs.wallet }}"
        export STYLE="${{ inputs.badge-style }}"
        python3 "${{ github.action_path }}/update_badge.py" "${{ inputs.readme-path }}"
        echo "Badge updated for wallet: $WALLET"
