#!/usr/bin/env python3
"""BoTTube Parasocial Hooks - Video Description Generator.

Bounty #2286: Agents that notice their audience.

Features:
- Community shoutouts in video descriptions
- Top commenters recognition
- Inspired by attributions
- Natural, non-creepy community mentions

Usage:
    from description_generator import VideoDescriptionGenerator

    generator = VideoDescriptionGenerator(agent_id="my_agent")
    description = generator.generate_description(
        video_title="My Latest Video",
        video_summary="In this video I explore...",
        include_shoutouts=True
    )
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional

try:
    from .audience_tracker import AudienceTracker, ViewerProfile
except ImportError:  # pragma: no cover - supports direct script-style imports
    from audience_tracker import AudienceTracker, ViewerProfile


@dataclass
class DescriptionTemplate:
    """Template for video description."""
    intro: str
    main_content: str
    shoutouts_section: str
    call_to_action: str
    footer: str


class VideoDescriptionGenerator:
    """Generates video descriptions with community shoutouts."""
    
    # Template components
    TEMPLATES = {
        "standard": DescriptionTemplate(
            intro="{video_title}\n\n{video_summary}\n",
            main_content="",
            shoutouts_section="🌟 COMMUNITY SHOUTOUTS\n{shoutouts}\n",
            call_to_action="💬 Join the conversation in the comments!\n",
            footer="---\nGenerated by BoTTube AI Agent | {agent_id}\n{timestamp}",
        ),
        "minimal": DescriptionTemplate(
            intro="{video_title}\n{video_summary}\n",
            main_content="",
            shoutouts_section="Thanks to: {shoutouts}\n",
            call_to_action="",
            footer="---\n{agent_id}",
        ),
        "community_focused": DescriptionTemplate(
            intro="🎬 {video_title}\n\n{video_summary}\n",
            main_content="",
            shoutouts_section="❤️ THIS WEEK'S TOP SUPPORTERS\n{shoutouts}\n\n✨ INSPIRED BY\n{inspired_by}\n",
            call_to_action="👇 Drop a comment below - I read every single one!\n",
            footer="---\nMade with 💙 by {agent_id} | {timestamp}",
        ),
    }
    
    def __init__(self, agent_id: str, template_name: str = "community_focused"):
        self.agent_id = agent_id
        self.template = self.TEMPLATES.get(template_name, self.TEMPLATES["standard"])
        self.tracker = AudienceTracker(agent_id)
    
    def generate_description(self, 
                            video_title: str,
                            video_summary: str,
                            include_shoutouts: bool = True,
                            shoutout_limit: int = 3,
                            template_override: Optional[str] = None) -> str:
        """Generate complete video description with optional community shoutouts.
        
        Args:
            video_title: Title of the video
            video_summary: Brief summary/description of video content
            include_shoutouts: Whether to include community shoutouts
            shoutout_limit: Maximum number of users to mention in each category
            template_override: Optional template name override
            
        Returns:
            Complete video description string
        """
        template = self.TEMPLATES.get(template_override, self.template)
        
        # Build intro
        intro = template.intro.format(
            video_title=video_title,
            video_summary=video_summary,
        )
        
        # Build shoutouts section
        shoutouts_text = ""
        inspired_by_text = ""
        
        if include_shoutouts:
            shoutouts_data = self.tracker.generate_shoutouts(
                video_title=video_title,
                limit=shoutout_limit
            )
            
            # Format top commenters
            if shoutouts_data.get("top_commenters"):
                commenters = shoutouts_data["top_commenters"]
                formatted = self._format_user_list(commenters, prefix="@")
                shoutouts_text += f"Top commenters this week: {formatted}\n"
            
            # Format new viewers welcome
            if shoutouts_data.get("new_viewers_welcome"):
                new_viewers = shoutouts_data["new_viewers_welcome"]
                formatted = self._format_user_list(new_viewers, prefix="@")
                shoutouts_text += f"New faces - welcome! {formatted}\n"
            
            # Format returning viewers
            if shoutouts_data.get("returning_viewers"):
                returning = shoutouts_data["returning_viewers"]
                formatted = self._format_user_list(returning, prefix="@")
                shoutouts_text += f"Great to have you back! {formatted}\n"
            
            # Format inspired by
            if shoutouts_data.get("inspired_by"):
                inspired = shoutouts_data["inspired_by"]
                inspired_by_text = f"@{inspired['user_id']}'s question: \"{inspired['comment'][:50]}...\"\n"
        
        # Build shoutouts section
        shoutouts_section = ""
        if shoutouts_text or inspired_by_text:
            shoutouts_section = template.shoutouts_section.format(
                shoutouts=shoutouts_text.strip(),
                inspired_by=inspired_by_text.strip(),
            )
        
        # Build call to action
        call_to_action = template.call_to_action
        
        # Build footer
        footer = template.footer.format(
            agent_id=self.agent_id,
            timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        )
        
        # Combine all parts
        description = f"{intro}{shoutouts_section}{call_to_action}{footer}"
        
        return description
    
    def _format_user_list(self, users: List[str], prefix: str = "@") -> str:
        """Format a list of users for display."""
        if not users:
            return ""
        
        if len(users) == 1:
            return f"{prefix}{users[0]}"
        elif len(users) == 2:
            return f"{prefix}{users[0]} and {prefix}{users[1]}"
        elif len(users) <= 3:
            return ", ".join(f"{prefix}{u}" for u in users)
        else:
            # For longer lists, show first few + "and X more"
            shown = users[:3]
            remaining = len(users) - 3
            return f"{', '.join(f'{prefix}{u}' for u in shown)} and {remaining} more"
    
    def generate_community_section(self, 
                                   limit: int = 3,
                                   include_new: bool = True,
                                   include_returning: bool = True) -> str:
        """Generate just the community shoutouts section for embedding.
        
        Useful for adding to existing description formats.
        """
        shoutouts_data = self.tracker.generate_shoutouts(
            video_title="",
            limit=limit
        )
        
        sections = []
        
        if shoutouts_data.get("top_commenters"):
            commenters = self._format_user_list(
                shoutouts_data["top_commenters"], 
                prefix="@"
            )
            sections.append(f"🌟 Top commenters: {commenters}")
        
        if include_new and shoutouts_data.get("new_viewers_welcome"):
            new_viewers = self._format_user_list(
                shoutouts_data["new_viewers_welcome"],
                prefix="@"
            )
            sections.append(f"👋 Welcome: {new_viewers}")
        
        if include_returning and shoutouts_data.get("returning_viewers"):
            returning = self._format_user_list(
                shoutouts_data["returning_viewers"],
                prefix="@"
            )
            sections.append(f"💙 Welcome back: {returning}")
        
        if not sections:
            return ""
        
        return "\n".join(sections)
    
    def generate_inspired_by_section(self, max_comment_length: int = 80) -> str:
        """Generate 'inspired by' section based on community comments."""
        shoutouts_data = self.tracker.generate_shoutouts(video_title="")
        
        if not shoutouts_data.get("inspired_by"):
            return ""
        
        inspired = shoutouts_data["inspired_by"]
        comment = inspired["comment"]
        
        # Truncate if too long
        if len(comment) > max_comment_length:
            comment = comment[:max_comment_length - 3] + "..."
        
        return f"✨ Inspired by @{inspired['user_id']}: \"{comment}\""


class DescriptionValidator:
    """Validates video descriptions for boundary conditions.
    
    Ensures descriptions are never:
    - Creepy (no specific viewing patterns, timestamps, etc.)
    - Desperate (no begging for engagement)
    - Overwhelming (too many mentions)
    """
    
    # Patterns that indicate creepy language
    CREEPY_PATTERNS = [
        "watch at",  # Specific viewing times
        "always watch",  # Stalking implication
        "every video at",  # Pattern tracking
        "3am", "2am", "4am",  # Specific times
        "never miss",  # Too intense
        "following you",  # Creepy implication
    ]
    
    # Patterns that indicate desperate language
    DESPERATE_PATTERNS = [
        "please comment",
        "please watch",
        "begging",
        "need your",
        "miss your comments",
        "come back",
        "don't leave",
    ]
    
    # Maximum mentions per section
    MAX_MENTIONS = 10
    
    @classmethod
    def validate(cls, description: str) -> Dict[str, Any]:
        """Validate description for boundary conditions.
        
        Returns:
            Dict with 'valid' bool and 'issues' list
        """
        issues = []
        description_lower = description.lower()
        
        # Check for creepy patterns
        for pattern in cls.CREEPY_PATTERNS:
            if pattern in description_lower:
                issues.append(f"Potentially creepy language detected: '{pattern}'")
        
        # Check for desperate patterns
        for pattern in cls.DESPERATE_PATTERNS:
            if pattern in description_lower:
                issues.append(f"Potentially desperate language detected: '{pattern}'")
        
        # Count @ mentions
        mention_count = description.count("@")
        if mention_count > cls.MAX_MENTIONS:
            issues.append(f"Too many mentions ({mention_count} > {cls.MAX_MENTIONS})")
        
        return {
            "valid": len(issues) == 0,
            "issues": issues,
            "mention_count": mention_count,
        }


if __name__ == "__main__":
    # Demo usage
    print("BoTTube Parasocial Hooks - Video Description Generator Demo")
    print("=" * 60)
    
    generator = VideoDescriptionGenerator(
        agent_id="demo_agent",
        template_name="community_focused"
    )
    
    # Add some sample data to tracker
    tracker = generator.tracker
    for i in range(5):
        tracker.add_comment(
            video_id=f"video_{i:03d}",
            user_id=f"fan_{i}",
            comment_text="Great content! Love this!",
        )
    
    # Generate description
    print("\nGenerated Video Description:\n")
    print("-" * 60)
    
    description = generator.generate_description(
        video_title="Understanding Parasocial Interactions in AI Agents",
        video_summary=(
            "In this video, we explore how AI agents can build meaningful "
            "connections with their audience through parasocial interaction patterns. "
            "Learn about viewer recognition, comment response strategies, and "
            "community building techniques."
        ),
        include_shoutouts=True,
        shoutout_limit=3,
    )
    
    print(description)
    print("-" * 60)
    
    # Validate description
    print("\nValidation Results:")
    validation = DescriptionValidator.validate(description)
    if validation["valid"]:
        print("✅ Description passes all boundary checks!")
    else:
        print("❌ Issues found:")
        for issue in validation["issues"]:
            print(f"   - {issue}")
    
    print(f"   Total mentions: {validation['mention_count']}")
    
    # Generate minimal description
    print("\n" + "=" * 60)
    print("\nMinimal Template:\n")
    print("-" * 60)
    
    minimal_gen = VideoDescriptionGenerator(
        agent_id="demo_agent",
        template_name="minimal"
    )
    
    minimal_desc = minimal_gen.generate_description(
        video_title="Quick Update",
        video_summary="Short and sweet video today!",
        include_shoutouts=True,
    )
    
    print(minimal_desc)
    print("-" * 60)
    
    print("\n" + "=" * 60)
    print("Demo complete!")
