apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustchain.fullname" . }}
  labels:
    {{- include "rustchain.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "rustchain.selectorLabels" . | nindent 4 }}
