/**
 * Vintage Hardware Museum - Exhibit Definitions
 * Real Elyan Labs hardware that mines RTC
 */

const EXHIBITS = [
  {
    id: 'ibm-power8',
    name: 'IBM POWER8 S824',
    type: 'Enterprise Server',
    year: 2014,
    tag: 'CENTERPIECE',
    position: { x: 0, z: 0 },
    scale: 2.0,
    color: 0x334455,
    glowColor: 0x00aaff,
    specs: {
      CPU: 'POWER8 12-core × 2 (SMT8)',
      Threads: '128 hardware threads',
      RAM: '512 GB DDR3 ECC',
      Storage: '4× 900GB SAS 10K',
      Network: '2× 10GbE',
      OS: 'Ubuntu 20.04 LTS',
    },
    lore: 'The crown jewel of Elyan Labs. Two POWER8 processors running 128 simultaneous threads mine RTC at unmatched throughput. Acquired from a decommissioned financial data center.',
    minerKey: 'power8-s824',
    antiquityMultiplier: 1.0,
    dimensions: { w: 3.5, h: 0.6, d: 2.2 },
  },
  {
    id: 'dell-c4130',
    name: 'Dell PowerEdge C4130',
    type: 'GPU Compute Cluster',
    year: 2016,
    tag: 'GPU FARM',
    position: { x: -6, z: -4 },
    scale: 1.4,
    color: 0x223344,
    glowColor: 0xff6600,
    specs: {
      GPUs: '4× NVIDIA Tesla P100 16GB',
      CPU: 'Xeon E5-2699 v4 (22-core)',
      RAM: '256 GB DDR4 ECC',
      Storage: '2× 1.92TB NVMe SSD',
      Power: '2× 1600W PSU',
      OS: 'Ubuntu 22.04 LTS',
    },
    lore: 'Four P100 datacenter GPUs in a dense 1U chassis. Originally built for ML training at a research institute. Now hashes RTC with CUDA kernels.',
    minerKey: 'dell-c4130',
    antiquityMultiplier: 1.0,
    dimensions: { w: 2.2, h: 0.2, d: 1.6 },
  },
  {
    id: 'powermac-g4-mdd',
    name: 'Power Mac G4 MDD',
    type: 'Vintage Workstation',
    year: 2003,
    tag: '2.5× ANTIQUITY',
    position: { x: 5, z: -4 },
    scale: 1.2,
    color: 0x888888,
    glowColor: 0x00ff88,
    specs: {
      CPU: 'PowerPC G4 7455 @ 1.25GHz × 2',
      RAM: '2 GB PC2700 DDR',
      Storage: '160 GB ATA HDD',
      GPU: 'ATI Radeon 9000 Pro 64MB',
      OS: 'Gentoo Linux PPC',
      Antiquity: '2.5× RTC bonus',
    },
    lore: 'The Mirrored Drive Door G4. Still boots. Its dual G4 processors earn 2.5× antiquity bonus mining RTC — proof that old iron never dies.',
    minerKey: 'powermac-g4-mdd',
    antiquityMultiplier: 2.5,
    dimensions: { w: 1.2, h: 1.8, d: 0.6 },
  },
  {
    id: 'powermac-g5',
    name: 'Power Mac G5 Dual',
    type: 'Vintage Workstation',
    year: 2004,
    tag: '2.5× ANTIQUITY',
    position: { x: 8, z: -2 },
    scale: 1.1,
    color: 0x999999,
    glowColor: 0x00ff88,
    specs: {
      CPU: 'PowerPC G5 970FX @ 2.0GHz × 2',
      RAM: '8 GB DDR2 ECC',
      Storage: '250 GB SATA HDD',
      GPU: 'NVIDIA GeForce 6600 256MB',
      Cooling: 'Liquid cooled CPU array',
      Antiquity: '2.5× RTC bonus',
    },
    lore: 'Apple\'s last PowerPC desktop. Liquid-cooled G5s hum at 65°C mining RTC with the 2.5× antiquity multiplier. The LCS still holds after 20 years.',
    minerKey: 'powermac-g5',
    antiquityMultiplier: 2.5,
    dimensions: { w: 1.1, h: 2.0, d: 0.6 },
  },
  {
    id: 'powerbook-g4',
    name: 'PowerBook G4 Collection',
    type: 'Vintage Laptops',
    year: 2002,
    tag: '2.5× ANTIQUITY',
    position: { x: -5, z: 4 },
    scale: 0.9,
    color: 0x777777,
    glowColor: 0xffcc00,
    specs: {
      Models: 'G4 12", 15" Ti, 17" Al',
      CPU: 'PowerPC G4 550–1.67GHz',
      RAM: '256 MB – 2 GB DDR',
      Storage: '40–120 GB ATA',
      Battery: 'Removed (AC-powered)',
      Antiquity: '2.5× RTC bonus',
    },
    lore: 'Three PowerBook G4s running 24/7: the titanium 15", and two aluminum models. Lids open, GPUs disabled, mining quietly at 2.5× antiquity rate.',
    minerKey: 'powerbook-g4',
    antiquityMultiplier: 2.5,
    dimensions: { w: 2.4, h: 0.1, d: 1.6 },
  },
  {
    id: 'sparcstation',
    name: 'SPARCstation Fleet',
    type: 'Vintage Workstations',
    year: 1993,
    tag: '2.5× ANTIQUITY',
    position: { x: 0, z: 6 },
    scale: 1.0,
    color: 0x886644,
    glowColor: 0xff8800,
    specs: {
      Models: 'SPARCstation 5 × 3 units',
      CPU: 'MicroSPARC-II 170MHz',
      RAM: '64 MB ECC',
      Storage: 'SCSI 2GB each',
      OS: 'NetBSD/sparc',
      Antiquity: '2.5× RTC bonus',
    },
    lore: 'Sun Microsystems workhorses from 1993. Running NetBSD on original hardware, these pizza-box SPARCstations mine RTC with maximum antiquity bonus.',
    minerKey: 'sparcstation',
    antiquityMultiplier: 2.5,
    dimensions: { w: 1.5, h: 0.2, d: 1.0 },
  },
  {
    id: 'laptop-486',
    name: '486/386 Laptop Collection',
    type: 'Retro Laptops',
    year: 1994,
    tag: '2.5× ANTIQUITY',
    position: { x: 5, z: 5 },
    scale: 0.85,
    color: 0x555544,
    glowColor: 0x88ff44,
    specs: {
      Models: 'IBM ThinkPad 486, Compaq LTE 386',
      CPU: 'i486 DX2 66MHz / 386SX 20MHz',
      RAM: '8 MB / 4 MB',
      Storage: 'CF card adapter',
      OS: 'FreeDOS + custom miner',
      Antiquity: '2.5× RTC bonus',
    },
    lore: 'Early 90s road warriors repurposed for blockchain glory. A custom DOS-based RTC miner runs on these machines, earning maximum antiquity multiplier.',
    minerKey: 'laptop-486',
    antiquityMultiplier: 2.5,
    dimensions: { w: 1.8, h: 0.08, d: 1.3 },
  },
  {
    id: 'cluster-rack',
    name: 'Elyan Labs Rack Array',
    type: 'Mixed Compute Rack',
    year: 2010,
    tag: 'INFRASTRUCTURE',
    position: { x: -8, z: 0 },
    scale: 1.3,
    color: 0x222233,
    glowColor: 0x8800ff,
    specs: {
      Units: '42U server rack',
      Nodes: '8× dual-Xeon nodes',
      Total: '96 CPU cores',
      RAM: '512 GB aggregate',
      Network: '10GbE switching fabric',
      Power: '208V 30A circuit',
    },
    lore: 'The backbone of Elyan Labs. Eight dual-Xeon nodes in a 42U rack providing steady RTC mining throughput alongside the POWER8 centerpiece.',
    minerKey: 'rack-array',
    antiquityMultiplier: 1.0,
    dimensions: { w: 0.8, h: 3.5, d: 1.2 },
  },
];

// Export for use by other modules
if (typeof module !== 'undefined') {
  module.exports = { EXHIBITS };
}
